services:
  # Full-stack service (Backend API + Frontend) with Firestore
  - type: web
    name: Tetronix
    env: node
    plan: free
    branch: master
    nodeVersion: 20
    buildCommand: npm install && npm run build
    startCommand: serve -s build
